[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - LOGS_CAPTURED - Started capturing logs in process (pid: 62972).
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - STEP_START - Started execution of step "raw_data_ingestion".
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - raw_data_ingestion - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/core_data using PickledObjectFilesystemIOManager...
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - LOADED_INPUT - Loaded input "core_data" using input manager "io_manager", from output "core_data" of step "core_data"
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - raw_data_ingestion - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/customer_interactions using PickledObjectFilesystemIOManager...
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - LOADED_INPUT - Loaded input "customer_interactions" using input manager "io_manager", from output "result" of step "customer_interactions"
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - raw_data_ingestion - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/usage_info using PickledObjectFilesystemIOManager...
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - LOADED_INPUT - Loaded input "usage_info" using input manager "io_manager", from output "result" of step "usage_info"
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - STEP_INPUT - Got input "core_data" of type "Any". (Type check passed).
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - STEP_INPUT - Got input "customer_interactions" of type "Any". (Type check passed).
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - STEP_INPUT - Got input "usage_info" of type "Any". (Type check passed).
[32m2025-07-02 17:58:33 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - raw_data_ingestion - Starting raw data ingestion
[32m2025-07-02 17:58:34 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - raw_data_ingestion - Storing raw core data
[32m2025-07-02 17:58:34 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 1afd4149-5b60-4671-be90-7b3346c95b89 - 62972 - raw_data_ingestion - STEP_FAILURE - Execution of step "raw_data_ingestion" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "raw_data_ingestion"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name raw_core_data does not exist!
Did you mean "database.raw_core_data"?

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/data_ingestion.py", line 36, in raw_data_ingestion
    conn.execute("""
[0m
